export const locationData = [
    {
        name: 'Christchurch',
        lat: -43.532055,
        long: 172.636230,
        altitude: 40,
        timezone: 'Pacific/Auckland',
        },
     {
        name: 'Adelaide',
        lat: -34.9285,
        long: 138.6007,
        altitude: 50,
        timezone: 'Australia/Adelaide',
        },
    {
        name: 'Melbourne',
        lat: -37.8136,
        long: 144.9631,
        altitude: 31,
        timezone: 'Australia/Melbourne',
        },
    {
        name: 'Sydney',
        lat: -33.8688,
        long: 151.2093,
        altitude: 30,
        timezone: 'Australia/Sydney',
        },
    {
        name: 'Brisbane',
        lat: -27.4698,
        long: 153.0251,
        altitude: 30,
        timezone: 'Australia/Brisbane',
        },
   {
        name: 'Auckland',
        lat: -36.8485,
        long: 174.7633,
        altitude: 30,
        timezone: 'Pacific/Auckland',
        },
    {
        name: 'Hobart',
        lat: -42.8821,
        long: 147.3272,
        altitude: 50,
        timezone: 'Australia/Hobart',
        },
    {
        name: 'Perth',
        lat: -31.9505,
        long: 115.8605,
        altitude: 30,
        timezone: 'Australia/Perth',
        },
    {
        name: 'Victor Harbor',
        lat: -35.5542,
        long: 138.6178,
        altitude: 30,
        timezone: 'Australia/Adelaide',
        },

    {
        name: 'Newcastle',
        lat: -32.9283,
        long: 151.7817,
        altitude: 30,
        timezone: 'Australia/Sydney',
    },
    {
        name: 'Wollongong',
        lat: -34.4278,
        long: 150.8931,
        altitude: 30,
        timezone: 'Australia/Sydney',
    },
    {
        name: 'Gold Coast',
        lat: -28.0167,
        long: 153.4000,
        altitude: 30,
        timezone: 'Australia/Brisbane',
    },
    {
        name: 'Canberra',
        lat: -35.2809,
        long: 149.1300,
        altitude: 578,
        timezone: 'Australia/Canberra',
    },
    {
        name: 'Darwin',
        lat: -12.4634,
        long: 130.8456,
        altitude: 50,
        timezone: 'Australia/Darwin',
    },
    {
        name: 'Alice Springs',
        lat: -23.6980,
        long: 133.8807,
        altitude: 500,
        timezone: 'Australia/North',
    },
    {
        name: 'Cairns',
        lat: -16.9186,
        long: 145.7781,
        altitude: 7,
        timezone: 'Australia/Queensland',
    },
    {
        name: 'Broome',
        lat: -17.9614,
        long: 122.2359,
        altitude: 50,
        timezone: 'Australia/Perth',
    },
    {
        name: 'Townsville',
        lat: -19.2589,
        long: 146.8169,
        altitude: 15,
        timezone: 'Australia/Queensland',
    },
    {
        name: 'Mount Gambier',
        lat: -37.8310,
        long: 140.7820,
        altitude: 50,
        timezone: 'Australia/Adelaide',
    },
    {
        name: 'Launceston',
        lat: -41.4545,
        long: 147.1369,
        altitude: 50,
        timezone: 'Australia/Tasmania',
    },
    {
        name: 'Mildura',
        lat: -34.2088,
        long: 142.1210,
        altitude: 50,
        timezone: 'Australia/Victoria',
    },
    {
        name: 'Black Heath',
        lat: -33.7123,
        long: 150.3119,
        altitude: 1065,
        timezone: 'Australia/Sydney',
    },
    {
        name: 'Broken Hill',
        lat: -31.9535,
        long: 141.4531,
        altitude: 330,
        timezone: 'Australia/Adelaide',
    },
    {
        name: 'Jamestown',
        lat: -33.2039,
        long: 138.6007,
        altitude: 50,
        timezone: 'Australia/Adelaide',
    },
    {
        name: 'Clare',
        lat: -33.8350,
        long: 138.6167,
        altitude: 50,
        timezone: 'Australia/Adelaide',
    },
    {
        name: 'Port Augusta',
        lat: -32.4958,
        long: 137.7652,
        altitude: 50,
        timezone: 'Australia/Adelaide',
    },
    {
        name: 'Coober Pedy',
        lat: -29.0134,
        long: 134.7544,
        altitude: 200,
        timezone: 'Australia/Adelaide',
    },
    {
        name: 'Wellington',
        lat: -41.2865,
        long: 174.7762,
        altitude: 50,
        timezone: 'Pacific/Auckland',
    },
   {
        name: 'Dunedin',
        lat: -45.8788,
        long: 170.5028,
        altitude: 15,
        timezone: 'Pacific/Auckland',
    },
    {
        name: 'Arthur\'s Pass',
        lat: -42.9581,
        long: 171.5516,
        altitude: 800,
        timezone: 'Pacific/Auckland',
    },
    {
        name: 'Queenstown',
        lat: -45.0312,
        long: 168.6626,
        altitude: 300,
        timezone: 'Pacific/Auckland',
    },
    {
        name: 'Nelson',
        lat: -41.2706,
        long: 173.2840,
        altitude: 50,
        timezone: 'Pacific/Auckland',
    },
   {
        name: 'Beijing',
        lat: 39.9042,
        long: 116.4074,
        altitude: 50,
        timezone: 'Asia/Shanghai',
    }, 
     {
        name: 'Tokyo',
        lat: 35.6895,
        long: 139.6917,
        altitude: 50,
        timezone: 'Asia/Tokyo',
    },
    {
        name: 'London',
        lat: 51.5074,
        long: -0.1278,
        altitude: 50,
        timezone: 'Europe/London',
    },
     {
        name: 'New York',
        lat: 40.7128,
        long: -74.0060,
        altitude: 10,
        timezone: 'America/New_York',
    },
     {
        name: 'Savannah',
        lat: 32.0809,
        long: -81.0912,
        altitude: 30,
        timezone: 'America/New_York',
    },
    {
        name: 'Los Angeles',
        lat: 34.0522,
        long: -118.2437,
        altitude: 30,
        timezone: 'America/Los_Angeles',
    },
   {
        name: 'Sedona',
        lat: 34.8697,
        long: -111.7609,
        altitude: 1300,
        timezone: 'America/Phoenix',
    },
     {
        name: 'Paris',
        lat: 48.8566,
        long: 2.3522,
        altitude: 35,
        timezone: 'Europe/Paris',
    },
     {
        name: 'Rome',
        lat: 41.9028,
        long: 12.4964,
        altitude: 50,
        timezone: 'Europe/Rome',
    },
    {
        name: 'Lauterbrunnen',
        lat: 46.5931,
        long: 7.9090,
        altitude: 800,
        timezone: 'Europe/Zurich',
    },
    {
        name: 'Zurich',
        lat: 47.3769,
        long: 8.5417,
        altitude: 400,
        timezone: 'Europe/Zurich',
    },
    {
        name: 'Lisbon',
        lat: 38.7223,
        long: -9.1393,
        altitude: 10,
        timezone: 'Europe/Lisbon',
    },
    {
        name: 'Geneva',
        lat: 46.2044,
        long: 6.1432,
        altitude: 400,
        timezone: 'Europe/Zurich',
    },
    {
        name: 'San Diego',
        lat: 32.7157,
        long: -117.1611,
        altitude: 30,
        timezone: 'America/Los_Angeles',
    },
    {
        name: 'Miami',
        lat: 25.7617,
        long: -80.1918,
        altitude: 30,
        timezone: 'America/New_York',
    },
    {
        name: 'Mexico City',
        lat: 19.4326,
        long: -99.1332,
        altitude: 2250,
        timezone: 'America/Mexico_City',
    },
    {
        name: 'Vancouver',
        lat: 49.2827,
        long: -123.1207,
        altitude: 30,
        timezone: 'America/Vancouver',
    },
    {
        name: 'Santiago',
        lat: -33.4489,
        long: -70.6693, 
        altitude: 500,
        timezone: 'America/Santiago',
    },
    {
        name: 'Buenos Aires',
        lat: -34.6037,
        long: -58.3816,
        altitude: 25,
        timezone: 'America/Argentina/Buenos_Aires',
    },
    {
        name: 'Rio de Janeiro',
        lat: -22.9068,
        long: -43.1729,
        altitude: 30,
        timezone: 'America/Sao_Paulo',
    },
    {
        name: 'Lima',
        lat: -12.0464,
        long: -77.0428,
        altitude: 154,
        timezone: 'America/Lima',
    },
    {
        name: 'Bogota',
        lat: 4.7110,
        long: -74.0721,
        altitude: 2640,
        timezone: 'America/Bogota',
    },
    {
        name: 'Atlanta',
        lat: 33.7490,
        long: -84.3880,
        altitude: 300,
        timezone: 'America/New_York',
    },
    {
        name: 'New Orleans',
        lat: 29.9511,
        long: -90.0715,
        altitude: 2,
        timezone: 'America/Chicago',
    },
    {
        name: 'Boston',
        lat: 42.3601,
        long: -71.0589,
        altitude: 30,
        timezone: 'America/New_York',
    },
    ]